Add conditional option to create cluster-admin
rh-mobb/ansible-rosa pull request #15
Opened 2023-09-06 13:19 UTC by MichaelMarkieta

Allow a user to prevent the hardcoding and automatic creation of the cluster-admin user

- Added bool variable `rosa_create_admin`, defaulted to true to not break current implementation
- Added conditional `when: rosa_create_admin` bool operator to run the create_admin task

2023-09-06 17:34 UTC, paulczar commented on roles/create_admin/tasks/main.yml
> +  when: rosa_create_admin
rather than checking here we should check in the /create-cluster.yaml playbook

```
- name: roles/create_admin
  when: rosa_create_admin | bool

2023-09-06 17:34 UTC, paulczar commented on roles/finish/tasks/main.yml
> +  when: rosa_create_admin
when: rosa_create_admin | bool

2023-09-06 17:36 UTC, paulczar requested changes
put the main feature gate for the create-admin role at the playbook vs inside the roll.

also we should use the `| bool` in the when statements so that we know for sure the variable will be treated as a boolean.

2023-09-07 01:54 UTC, MichaelMarkieta commented
Sorry @paulczar, I accidentally overwrote your `| bool` casting, fixed it in a second commit. I think we're ready now.

2023-09-07 13:35 UTC, paulczar approved these changes

2023-09-07 13:35 UTC, merged