Added BYOK KMS functionality for Rosa STS classic cluster
rh-mobb/ansible-rosa pull request #18
Opened 2023-09-21 15:43 UTC by ValentinoUberti

Added BYOK KMS automated procedure following the mobb guidelines https://mobb.ninja/docs/rosa/kms/

Vars example in ./environment/private-link-kms/group_vars/all.yaml

2023-09-28 23:27 UTC, scottd018 requested changes

2023-09-28 23:27 UTC, scottd018 commented on README.md
> +
Small nit here, but let's only leave 1-2 spaces between sections.  E.g. lines 116-121 can be removed.

2023-09-28 23:27 UTC, scottd018 commented on create-cluster.yaml
> +    # Create operator-roles
Remove lines 27-29.  These looks like comments to remind of future work to perform (which is already done)

2023-09-28 23:27 UTC, scottd018 commented on environment/private-link-kms/group_vars/all.yaml
> +rosa_kms_key_arn: "" #arn:aws:kms:us-east-2:<redacted>:key/<redacted>
Rather than creating a completely separate environment file for private-link-kms, I feel it's better to move line 5 here into the `environment/private-link/group_vars/all.yaml` file (the private link specific file).  Otherwise we create an unmanageable number of one off scenarios to manage in the environment directory.

2023-09-28 23:27 UTC, scottd018 commented on plugins/module_utils/ocm.py
> +
remove lines 129,131.

2023-09-28 23:27 UTC, scottd018 commented on plugins/module_utils/ocm.py
> +    #rosa sts kms is rosa classic
remove lines 166,167

2023-09-29 05:49 UTC, ValentinoUberti commented on README.md
> +
Done

2023-09-29 05:52 UTC, ValentinoUberti commented on create-cluster.yaml
> +    # Create operator-roles
Done

2023-09-29 05:52 UTC, ValentinoUberti commented on plugins/module_utils/ocm.py
> +
Done

2023-09-29 05:52 UTC, ValentinoUberti commented on plugins/module_utils/ocm.py
> +    #rosa sts kms is rosa classic
Done

2023-09-29 05:53 UTC, ValentinoUberti commented on environment/private-link-kms/group_vars/all.yaml
> +rosa_kms_key_arn: "" #arn:aws:kms:us-east-2:<redacted>:key/<redacted>
Done. I've also updated the README.md

2023-09-29 16:33 UTC, scottd018 approved these changes

2023-09-29 16:34 UTC, merged